### ISSUE TITLE
Bootstrap installation with module TCL does not find module command

### ISSUE THREAD

**Issue by menzzana** [hpcugent/easybuild#149] opened 2015-09-01 10:00 UTC
Hi I cannot get bootstrap install to work. See transcript below.
I have module TCL and ican directly type module help, and modulecmd.tcl, which should
be detected by the script, but I still recieve the same error.

What could be the cause?

----------------------------------------------------------------------------------------------------------------------------------
$ python bootstrap_eb.py $PREFIX
[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: modulecmd, lmod, modulecmd.tcl
Check the output of 'type module' to determine the location of the module command you are using.
$ modulecmd.tcl 
$ echo $PATH
build:/usr/local/bin:/usr/bin
$ type module
module is a function
module () 
{ 
    eval `$TCLSH /pdc/modules/etc/modulecmd.tcl bash $*`
}
$ export PATH=/pdc/modules/etc:$PATH
$ python bootstrap_eb.py $PREFIX
[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: modulecmd, lmod, modulecmd.tcl
Check the output of 'type module' to determine the location of the module command you are using.

**Comment by boegel** [comment] 2015-09-01 10:06
@menzzana: what does `which modulecmd.tcl` produce after you've updated `$PATH`?
Does the `modulecmd.tcl` script have execution permission bits set?

**Comment by menzzana** [comment] 2015-09-01 11:02
Thanks for quick feedback.
When running which I get this output...

which modulecmd.tcl
/pdc/modules/etc/modulecmd.tcl

Also I can execute it. Both by the normal

module help

or with 

modulecmd.tcl bash help

Which provides the same output

**Comment by boegel** [comment] 2015-09-01 11:06
Please try the bootstrap installation in debug mode, capture the output and make it available somehow (e.g. via https://gist.github.com):

```shell
export EASYBUILD_BOOTSTRAP_DEBUG=1
# replace <prefix> with a (test) installation prefix of your choice
python bootstrap_eb.py <prefix> 2>&1 | tee eb_bootstrap.log
```

**Comment by menzzana** [comment] 2015-09-01 11:12
ok. I added the log at https://gist.github.com/menzzana/f71074d804a258bd90c0

**Comment by boegel** [comment] 2015-09-01 11:25
Thanks, that helps.

Please try applying this patch to the bootstrap script, let me know if it helps:

```
diff --git a/easybuild/scripts/bootstrap_eb.py b/easybuild/scripts/bootstrap_eb.py
index c8a14b9..1784078 100755
--- a/easybuild/scripts/bootstrap_eb.py
+++ b/easybuild/scripts/bootstrap_eb.py
@@ -161,7 +161,7 @@ def check_module_command(tmpdir):
     for modcmd in known_module_commands:
         cmd = "%s python help" % modcmd
         os.system("%s > %s 2>&1" % (cmd, out))
-        modcmd_re = re.compile('module\s.*command\s')
+        modcmd_re = re.compile('module\s.*command\s|ModulesTcl')
         txt = open(out, "r").read()
         debug("Output from %s: %s" % (cmd, txt))
         if modcmd_re.search(txt):
```

**Comment by menzzana** [comment] 2015-09-01 11:39
Yes that solved the problem and my modulecmd.tcl was detected, but then I recieved other errors further down the execution...

== temporary log file in case of crash /tmp/eb-cXxCHA/easybuild-LJzPXt.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 658, in <module>
    main()
  File "bootstrap_eb.py", line 492, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 430, in stage2
    easybuild_main()
  File "/tmp/tmpCRqElw/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.2.0-py2.7.egg/easybuild/main.py", line 230, in main
    modlist = session_module_list(testing=testing)  # build options must be initialized first before 'module list' works
  File "/tmp/tmpCRqElw/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.2.0-py2.7.egg/easybuild/tools/testing.py", line 145, in session_module_list
    modtool = modules_tool(testing=testing)
  File "/tmp/tmpCRqElw/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.2.0-py2.7.egg/easybuild/tools/modules.py", line 972, in modules_tool
    return modules_tool_class(mod_paths=mod_paths, testing=testing)
  File "/tmp/tmpCRqElw/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.2.0-py2.7.egg/easybuild/tools/modules.py", line 183, in __init__
    self.set_and_check_version()
  File "/tmp/tmpCRqElw/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.2.0-py2.7.egg/easybuild/tools/modules.py", line 217, in set_and_check_version
    self.VERSION_OPTION, txt)
easybuild.tools.build_log.EasyBuildError: "Failed to determine version from option '' output: "
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x28d0aa0> ignored

**Comment by menzzana** [comment] 2015-09-01 11:40
Sorry...

added output with gist at https://gist.github.com/menzzana/fb9e6bc34fa3b8519111

**Comment by boegel** [comment] 2015-09-01 11:50
It's OK to copy-paste output straight into this issue, as long as it's limited to about a screen full of lines, don't worry.

I was expecting the debug output to be a lot bigger, hence my suggestion to use a gist.

The problem is that EasyBuild is failing to extract the version for your `modulecmd.tcl`... It should produce a nice error message rather than going down hard like this though...

Currently, EasyBuild uses this a version regex for `modulecmd.tcl` (see https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/tools/modules.py#L707):

```
VERSION_REGEXP = r'^Modules\s+Release\s+Tcl\s+(?P<version>\d\S*)\s'
```

But in the output of `modulecmd.tcl` it's parsing, you have this:

```
ModulesTcl 0.101/$Revision: 1.47 $:
```

We can enhance the regular expression we use, but I'd like to figure out why we've never run into this before... Where does this `modulecmd.tcl` come from?

And why `modulecmd.tcl`, rather than the more common C/Tcl combo (or the modern alternative Lmod)?

It's possible that you will run into more problems after we get this aspect fixed, if this `modulecmd.tcl` behaves differently than how EasyBuild expects...

**Comment by menzzana** [comment] 2015-09-01 12:19
I talked to the guys in charge of the machines, and apparently in 2005 they switched from the C version to the pure Tcl version since the C version was not updated anymore. Now this seems to be the other way around and our newest Cray is pre-configured with 3.2.10.
The machine that I am trying to install eb on did not have it at all, and by default they installed the Tcl version. It is supposed to be the standard version downloaded from http://modules.cvs.sourceforge.net/viewvc/modules/modules/tcl/

But since cray has already 3.2.10 and we run into problems with easybuild and perhaps others, 
we have now decided that we will scrap this and install 3.2.10 on the new machine as well.

Thanks anyway for your help, and at least you know there can be an issue with systems using modulecmd.tcl :-)

**Comment by boegel** [comment] 2015-09-03 07:32
It looks like that's a very old version of `modulecmd.tcl`, since the last revision is `1.147`, which is already two years old (see http://modules.cvs.sourceforge.net/viewvc/modules/modules/tcl/modulecmd.tcl?revision=1.147&view=markup).

The revision you're running here is `1.47`, which is dated Nov'04 (see http://modules.cvs.sourceforge.net/viewvc/modules/modules/tcl/modulecmd.tcl?revision=1.47&view=markup), uses a different format for reporting the version, as mentioned above.

Good to hear you're going forward with the Tcl/C version 3.2.10, that's probably the most common version.

At some point, you may want to consider *Lmod* (https://www.tacc.utexas.edu/research-development/tacc-projects/lmod). It's an actively maintained and vastly superior modules tool, which is 99% compatible with module files in Tcl syntax (so most likely, you wouldn't need to touch your module files at all).
EasyBuild has good support for Lmod, and it will further improve in the future (i.e. support will be added for more of the Lmod-specific features).

I'm going to close this issue since I don't feel it requires further action -- supporting a 10+ (!) year old modules tool is probably not worth the trouble...

**Closed by boegel** 2015-09-03 07:32 UTC
