### ISSUE TITLE
EasyBuild fails when used with both GC3Pie and --try options

### ISSUE THREAD

**Issue by dominikborkowski** [hpcugent/easybuild#141] opened 2015-08-06 15:03 UTC
When using EB with GC3Pie backend _and_ --try options, the resulting tweaked easyconfigs are placed in a temporary location, typically in /tmp on the head/login node. Consequent easybuild instances executed on the compute nodes do not have access to those configs and they fail.

Example working executing:

eb sed-4.2.2-goolf-1.4.10.eb --robot --job --job-cores=12 --job-backend=GC3Pie --job-backend-config=/apps/easybuild/config/gc3pie/sfxsmp_q.conf

Example execution that fails:

eb sed-4.2.2-goolf-1.4.10.eb --robot --job --job-cores=12 --job-backend=GC3Pie --job-backend-config=/apps/easybuild/config/gc3pie/sfxsmp_q.conf  --try-software-version=4.2.1

The error found in ~/.gc3pie_jobs/lrms_job.XXXXXXXXXX/sed-4.2.1-goolf.eNNNNNN is:

ERROR: Can't find path /tmp/eb-Prt28j/tweaked_easyconfigs/sed-4.2.1-goolf-1.4.10.eb

Thanks!

**Comment by dominikborkowski** [comment] 2015-08-06 15:04
Forgot to tag @ocaisa

**Comment by ocaisa** [comment] 2015-08-06 15:09
You can avoid this issue by setting a globally accessible temp area as an eb option, e.g.,
```--tmpdir=$HOME/TMP```

**Comment by boegel** [comment] 2015-08-06 15:19
A proper fix for this would be to let the submitted job handle the tweaking, rather than tweaking first and then submitting the job.

**Comment by boegel** [comment] 2016-01-23 13:14
duplicate of https://github.com/hpcugent/easybuild-framework/issues/1355, let's follow-up there

**Closed by boegel** 2016-01-23 13:14 UTC
