### ISSUE TITLE
PGI installation not working on Debian

### ISSUE THREAD

**Issue by geimer** [hpcugent/easybuild#217] opened 2016-05-12 08:17 UTC
After installing PGI 15.10 using EasyBuild on a Debian 7.10 system, I tried to compile a simple "Hello world" example.  Unfortunately, it failed...  Unloading the `binutils/2.25` module and using the system-provided one solved the issue.  On the other hand, using GCC or Intel compilers with the same `binutils` module loaded worked w/o any issues.  See below for a transcript of what I did.

My suspicion is that this has something to do with Debian's multiarch setup.  However, it is still unclear to me whether this is a binutils or PGI configuration issue.  I also haven't tried PGI 16.3 yet.

```
$ export LM_LICENSE_FILE=...
$ eb GCC-4.9.3-2.25.eb PGI-15.10-GCC-4.9.3-2.25.eb iccifort-2016.0.109-GCC-4.9.3-2.25.eb -r
        [...]
$ module load PGI
$ module list

Currently Loaded Modules:
  1) GCCcore/4.9.3   2) binutils/2.25   3) PGI/15.10-GCC-4.9.3-2.25

$ pgcc -o hello hello.c
<eb_prefix>/software/Compiler/GCCcore/4.9.3/binutils/2.25/bin/ld: cannot find -lpthread
<eb_prefix>/software/Compiler/GCCcore/4.9.3/binutils/2.25/bin/ld: cannot find -lm
<eb_prefix>/software/Compiler/GCCcore/4.9.3/binutils/2.25/bin/ld: cannot find -lc
$ module unload binutils
$ module list

Currently Loaded Modules:
  1) GCCcore/4.9.3   2) PGI/15.10-GCC-4.9.3-2.25

$ pgcc -o hello hello.c
$ ls
hello   hello.c
$ module purge
$ module load GCC
$ module list

Currently Loaded Modules:
  1) GCCcore/4.9.3   2) binutils/2.25   3) GCC/4.9.3-2.25

$ gcc -o hello hello.c
$ ls
hello   hello.c
$ module purge
$ module load iccifort
$ module list

Currently Loaded Modules:
  1) GCCcore/4.9.3    4) icc/2016.0.109-GCC-4.9.3-2.25
  2) binutils/2.25    5) ifort/2016.0.109-GCC-4.9.3-2.25
  3) GCC/4.9.3-2.25   6) iccifort/2016.0.109-GCC-4.9.3-2.25

$ icc -o hello hello.c
$ ls
hello   hello.c
```

**Comment by boegel** [comment] 2016-05-12 08:27
@geimer: hmm, maybe PGI doesn't take `$LIBRARY_PATH` into account (it's defined by your `GCCcore` module, right?), and only find the system `libm` (which is not compatible with the `ld` being used)?

Can you try running the failing `pgcc` command with `-v` added for more verbose output?

Others have had similar issues (back in the stone age): http://www.pgroup.com/userforum/viewtopic.php?p=14155&sid=cfc0911822d86d382b41a7571d91e813

This may also be helpful: https://software.intel.com/en-us/articles/error-ld-cannot-find-lm/.
As suggested there, can you try adding `-L$EBROOTGCCORE/lib` to the command line (seems like explicitly adding `-lm` is not needed).

Or, maybe the `libm` in your GCCcore installation is in `lib64`, and EB doesn't add `lib64` to `$LIBRARY_PATH`?

**Comment by geimer** [comment] 2016-05-12 08:51
@boegel: There is no `libm` in the GCCcore installation.  It always comes from the system (like `libc`).  On a 64-bit x86 Debian system with multiarch, it is located in `/usr/lib/x86_64-linux-gnu`, which is explicitly `-L`-ed by GCC and Intel, but not by PGI.  Unfortunately, adding this path to `$LIBRARY_PATH` doesn't help, but explicitly adding it on the command line does.

I vaguely remember that I once put `-L/usr/lib/x86_64-linux-gnu` in a `siterc` file in PGI's `bin` directory, but this caused problems later on so I removed it again -- and things magically continued to work (maybe due to an intermittent binutils update?).  But so far, I've always used the system-provided binutils.

All of this somehow suggests to me that there is some magic required on the binutils side to always correctly handle multiarch...

**Comment by boegel** [comment] 2016-05-12 08:55
@geimer so, we should trace down how binutils is built for multiarch on Debian?

**Comment by geimer** [comment] 2016-05-12 09:20
@boegel: Urgh... apparently Debian patches binutils.  There is a 220+ line patch for 2.25, and a 350+ line patch for 2.26 addressing multiarch lib paths -- which may even rely on the way the build is triggered from the `debian/rules` file...  Here is the ChangeLog entry from April 2014 when it was added:
```
  * 129_multiarch_libpath.patch: Fix to search multiarch dirs, only needed
    for a minority of packages still using ld directly for linking instead
    of the recommended use of gcc.
```
  I don't think EB wants get into that business...

**Comment by boegel** [comment] 2016-05-12 09:22
@geimer: I would prefer staying away from patching binutils, yes. Although, it the patch is non-destructive on other OSs, it's worth considering.

Maybe for PGI we need to somehow tell it to consider those extra paths, via `$LDFLAGS`?

That should be fairly easy to do in the PGI toolchain compiler support...

**Comment by geimer** [comment] 2016-05-12 11:12
@boegel: Whether the patches are non-destructive is hard to say, IMHO.

W.r.t. extending `$LDFLAGS`: There are also people out there that *develop* their own software and need to be able to compile stuff w/o EB :-)  And for them, setting extra `$LDFLAGS` in the framework wouldn't help.

BTW: Apparently `$LIBRARY_PATH` is ignored by the PGI compilers.  However, the GCCcore stuff is correctly picked up via the `localrc` file generated by the `makelocalrc` script run during installation.  To make `$LIBRARY_PATH` work, PGI proposes a workaround on their web pages, see https://www.pgroup.com/support/link.htm#lib_path_ldflags.

Note that there is a typo in the code snippet.  The second line should read `$LIBRARY_PATH` from the environment, not `$LD_LIBRARY_PATH`.  Maybe that is something we would want in any case?  If so, it should be straightforward to add `/usr/lib/x86_64-linux-gnu` to `$LIBRARY_PATH` when on a Debian/Ubuntu system, maybe even directly from the PGI easyblock.

**Comment by boegel** [comment] 2016-05-12 11:16
@geimer that looks like something we should look into, indeed...

Can you open a dedicated issue for this in the easyblocks repository?

Pushing in the Debian-specific path seems like a viable workaround.

**Comment by boegel** [comment] 2016-05-12 12:32
@geimer let's close this, and follow up in https://github.com/hpcugent/easybuild-easyblocks/issues/918, now that we know the cause of the issue?

**Comment by geimer** [comment] 2016-05-12 12:43
@boegel Yep, makes sense. If the `siterc` file approach bites us at some point, we can still reopen it.

**Closed** 2016-05-12 12:43 UTC

**Comment by cponder** [comment] 2018-06-25 18:55
I just ran into this same problem in a very specific case.
What I have to point out, is that the easybuild version of ld is connecting different directories than the system ld.
Comparing the output of the two commands

       ld -verbose | fgrep SEARCH_DIR
       /gpfs/sw/software/binutils/2.26/bin/ld -verbose | fgrep SEARCH_DIR

you get different lists; the second (easybuild) one also includes some nonexistant directories.
I understand that there are some incompatibilities between GCC & PGI etc., but this is a real bug.

**Comment by akesandgren** [comment] 2018-06-26 05:34
Are you saying that the nonexistant dirs are a bug or that /usr/lib/x86_64-linux-gnu (and /lib/x86...) is missing is the bug?

The normal system ld also include nonexisting dirs on Ubuntu at least.
Though I still haven't seen an actual problem with this. 
On the other hand i haven't had time to use the PGI compiler much yet.

**Comment by cponder** [comment] 2018-06-26 14:16
The easybuild binutils/ld includes these directories that don't exist:

             /gpfs/sw/software/binutils/2.26/x86_64-pc-linux-gnu/lib64
             /gpfs/sw/software/binutils/2.26/lib64
             /usr/local/lib64

The first 2 are easybuild-specific so I'd expect it to have built them, but it doesn't, which looks like a bug to me. Also, to me, it's a bug that the easybuild ld doesn't copy all the paths from the system ld and re-map the ones that it generates. That would preserve the debian-specific paths.

**Comment by cponder** [comment] 2018-06-26 17:04
These other directories are not prefixed with the easybuild path parameter:
      /usr/local/lib64               /usr/local/lib
      /usr/lib64                       /usr/lib
      /lib64                             /lib
but they are included nonetheless. So that;s not the whole reason that /usr/local/lib/x86_64-linux-gnu was neglected. Besides, I don't see any way to fix this using the prefix-paramater; if we used, say,
     --prefix=/usr/local/lib/x86_64-linux-gnu
we would just end up with incorrect paths like
     /usr/local/lib/x86_64-linux-gnu/lib64
for example.
